"""message

Revision ID: 17a6519e8726
Revises: 
Create Date: 2023-05-19 08:45:23.684118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a6519e8726'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('male_class_image', sa.String(), nullable=True),
    sa.Column('male_class_sprite_up', sa.String(), nullable=True),
    sa.Column('male_class_sprite_left', sa.String(), nullable=True),
    sa.Column('male_class_sprite_right', sa.String(), nullable=True),
    sa.Column('male_class_sprite_down', sa.String(), nullable=True),
    sa.Column('female_class_image', sa.String(), nullable=True),
    sa.Column('female_class_sprite_up', sa.String(), nullable=True),
    sa.Column('female_class_sprite_left', sa.String(), nullable=True),
    sa.Column('female_class_sprite_right', sa.String(), nullable=True),
    sa.Column('female_class_sprite_down', sa.String(), nullable=True),
    sa.Column('lvl', sa.Integer(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('mg', sa.Integer(), nullable=True),
    sa.Column('strg', sa.Integer(), nullable=True),
    sa.Column('defn', sa.Integer(), nullable=True),
    sa.Column('mind', sa.Integer(), nullable=True),
    sa.Column('intl', sa.Integer(), nullable=True),
    sa.Column('spd', sa.Integer(), nullable=True),
    sa.Column('evad', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('lname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(), nullable=False),
    sa.Column('character_sex', sa.String(), nullable=False),
    sa.Column('character_region', sa.Enum('Nemar', 'Cyneil', 'Corize', 'Naurra Isles', 'Ausstero'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('class_name_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_name_id'], ['class_names.id'], name=op.f('fk_characters_class_name_id_class_names')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_characters_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knight_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=True),
    sa.Column('skill_description', sa.String(), nullable=True),
    sa.Column('skill_cost', sa.Integer(), nullable=True),
    sa.Column('skill_level', sa.Integer(), nullable=True),
    sa.Column('skill_icon', sa.String(), nullable=True),
    sa.Column('class_name_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_name_id'], ['class_names.id'], name=op.f('fk_knight_skills_class_name_id_class_names')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_inventories_character_id_characters')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventories')
    op.drop_table('knight_skills')
    op.drop_table('characters')
    op.drop_table('users')
    op.drop_table('class_names')
    # ### end Alembic commands ###
